# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
env: staging
replicaCount: 1
host: fieldonline-staging.test-en-apps.euro.iberdrola.local
serviceName: fieldonline-data-adapter-service
image:
  tag: v1
  pullPolicy: Always
  imagePullSecretName: docker-registry-secret
